package com.vaccine.domain;

public enum NotificationType {
    BOOKING_CONFIRMED,
    VACCINATION_COMPLETED,
    APPOINTMENT_REMINDER_48H,
    APPOINTMENT_REMINDER_24H,
    SECOND_DOSE_REMINDER_48H,
    SECOND_DOSE_REMINDER_24H,
    SLOT_LIVE,
    SLOT_STARTING_SOON,
    WAITLIST_PROMOTED,
    FEEDBACK_REPLY,
    CONTACT_REPLY,
    BIRTHDAY,
    SYSTEM
}
