spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:vaccination_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      data-locations: classpath:data-complete.sql
  logging:
    level:
      root: INFO
      com.vaccine: DEBUG
app:
  seed:
    enabled: true
security:
  jwt:
    secret: vax-local-secret
