-- Reserved for non-sensitive demo catalog data only.
-- This file must never contain login credentials, seeded administrator accounts,
-- plaintext passwords, password hashes intended for shared reuse, API keys, or JWT secrets.
