-- Reserved for optional local sample data.
-- Do not add credentials, JWT material, default admin accounts, or reusable password hashes here.
-- Provision users and administrators through runtime environment variables, secure bootstrap tooling,
-- or manual admin workflows outside source control.
