-- Roles
INSERT INTO roles (name, description) VALUES ('SUPER_ADMIN', 'Super Administrator with full access');
INSERT INTO roles (name, description) VALUES ('ADMIN', 'Administrator with limited access');
INSERT INTO roles (name, description) VALUES ('USER', 'Regular user');

-- Vaccination Centers
INSERT INTO vaccination_centers (name, address, city, state, pincode, latitude, longitude, phone, email, capacity_per_day, is_active) VALUES ('City General Hospital', '123 Main Road, Civil Lines', 'Delhi', 'Delhi', '110001', 28.6139, 77.2090, '011-12345678', 'cgh@vaccinesystem.com', 500, true);
INSERT INTO vaccination_centers (name, address, city, state, pincode, latitude, longitude, phone, email, capacity_per_day, is_active) VALUES ('Metro Medical Center', '456 Metro Station Road', 'Mumbai', 'Maharashtra', '400001', 19.0760, 72.8777, '022-23456789', 'mmc@vaccinesystem.com', 400, true);
INSERT INTO vaccination_centers (name, address, city, state, pincode, latitude, longitude, phone, email, capacity_per_day, is_active) VALUES ('Tech City Clinic', '789 Tech Park, Electronic City', 'Bangalore', 'Karnataka', '560100', 12.9180, 77.6640, '080-34567890', 'tcc@vaccinesystem.com', 300, true);
INSERT INTO vaccination_centers (name, address, city, state, pincode, latitude, longitude, phone, email, capacity_per_day, is_active) VALUES ('Green Valley Hospital', '321 Green Avenue', 'Chennai', 'Tamil Nadu', '600001', 13.0827, 80.2707, '044-45678901', 'gvh@vaccinesystem.com', 350, true);
INSERT INTO vaccination_centers (name, address, city, state, pincode, latitude, longitude, phone, email, capacity_per_day, is_active) VALUES ('Lake View Center', '654 Lake Shore Road', 'Hyderabad', 'Telangana', '500001', 17.3850, 78.4867, '040-56789012', 'lvc@vaccinesystem.com', 450, true);

-- Vaccination Drives
INSERT INTO vaccination_drives (name, description, vaccine_name, vaccine_manufacturer, min_age, max_age, doses_required, dose_gap_days, center_id, start_date, end_date, start_time, end_time, total_slots, available_slots, is_active) VALUES ('COVID-19 Vaccination Drive 2026', 'Free COVID-19 vaccination for all eligible citizens', 'Covishield', 'Oxford/AstraZeneca', 18, 60, 2, 84, 1, '2026-03-01', '2026-12-31', '09:00', '17:00', 5000, 5000, true);
INSERT INTO vaccination_drives (name, description, vaccine_name, vaccine_manufacturer, min_age, max_age, doses_required, dose_gap_days, center_id, start_date, end_date, start_time, end_time, total_slots, available_slots, is_active) VALUES ('Flu Vaccination Campaign', 'Annual flu vaccination campaign', 'Influvac', 'Abbott', 5, 100, 1, 0, 2, '2026-03-01', '2026-12-31', '08:00', '16:00', 4000, 4000, true);
INSERT INTO vaccination_drives (name, description, vaccine_name, vaccine_manufacturer, min_age, max_age, doses_required, dose_gap_days, center_id, start_date, end_date, start_time, end_time, total_slots, available_slots, is_active) VALUES ('Pediatric Immunization Program', 'Routine immunization for children', 'Pentavac', 'Serum Institute', 0, 12, 3, 30, 3, '2026-03-01', '2026-12-31', '09:00', '15:00', 3000, 3000, true);
INSERT INTO vaccination_drives (name, description, vaccine_name, vaccine_manufacturer, min_age, max_age, doses_required, dose_gap_days, center_id, start_date, end_date, start_time, end_time, total_slots, available_slots, is_active) VALUES ('Hepatitis B Adult Drive', 'Hepatitis B vaccination for adults', 'Hepavax', 'Johnson and Johnson', 18, 100, 3, 30, 4, '2026-03-01', '2026-12-31', '10:00', '18:00', 3500, 3500, true);
INSERT INTO vaccination_drives (name, description, vaccine_name, vaccine_manufacturer, min_age, max_age, doses_required, dose_gap_days, center_id, start_date, end_date, start_time, end_time, total_slots, available_slots, is_active) VALUES ('Typhoid Awareness Drive', 'Typhoid vaccination awareness', 'Typbar-TCV', 'Bharat Biotech', 2, 100, 1, 0, 5, '2026-03-01', '2026-12-31', '09:00', '17:00', 4500, 4500, true);
