package com.vaccine.tools;

import java.io.BufferedWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import org.flywaydb.core.Flyway;

public final class DatabaseMigrationTool {
    private static final Pattern MYSQL_URL_PATTERN =
        Pattern.compile("^jdbc:mysql://(?<hostport>[^/]+)/(?<db>[^?]+)(?<query>\\?.*)?$", Pattern.CASE_INSENSITIVE);
    private static final Pattern MIGRATION_FILE_PATTERN =
        Pattern.compile("^V(?<version>[0-9]+)__.*\\.sql$", Pattern.CASE_INSENSITIVE);
    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm:ss");

    private DatabaseMigrationTool() {
    }

    public static void main(String[] args) throws Exception {
        MigrationConfig config = MigrationConfig.fromEnvironment();
        Files.createDirectories(config.outputFile().getParent());
        Files.createDirectories(config.validationFile().getParent());

        Class.forName("org.h2.Driver");
        Class.forName("com.mysql.cj.jdbc.Driver");

        try (
            Connection source = DriverManager.getConnection(config.sourceUrl(), config.sourceUsername(), config.sourcePassword());
            Connection targetServer = DriverManager.getConnection(config.targetServerUrl(), config.targetUsername(), config.targetPassword())
        ) {
            System.out.println("Starting H2 to MySQL migration.");
            createTargetDatabaseIfMissing(targetServer, config.targetDatabase());

            try (Connection target = DriverManager.getConnection(config.targetUrl(), config.targetUsername(), config.targetPassword())) {
                target.setAutoCommit(false);

                Map<String, TableInfo> tables = loadTables(source);
                if (tables.isEmpty()) {
                    throw new IllegalStateException("No application tables were found in the H2 source database.");
                }

                ensureSafeTargetState(target, config.allowTargetReset());

                try (BufferedWriter writer = Files.newBufferedWriter(config.outputFile(), StandardCharsets.UTF_8)) {
                    writer.write("-- Generated by DatabaseMigrationTool at " + LocalDateTime.now() + System.lineSeparator());
                    writer.write("SET FOREIGN_KEY_CHECKS = 0;" + System.lineSeparator() + System.lineSeparator());

                    for (TableInfo table : tables.values()) {
                        String createSql = buildCreateTableSql(table);
                        executeStatement(target, createSql);
                        writer.write(createSql);
                        writer.write(System.lineSeparator());
                        writer.write(System.lineSeparator());
                    }

                    for (TableInfo table : tables.values()) {
                        exportAndImportRows(source, target, table, writer);
                    }

                    for (TableInfo table : tables.values()) {
                        for (ForeignKeyInfo foreignKey : table.foreignKeys()) {
                            String foreignKeySql = buildForeignKeySql(table.name(), foreignKey);
                            executeStatement(target, foreignKeySql);
                            writer.write(foreignKeySql);
                            writer.write(System.lineSeparator());
                        }
                        if (!table.foreignKeys().isEmpty()) {
                            writer.write(System.lineSeparator());
                        }
                    }

                    writer.write("SET FOREIGN_KEY_CHECKS = 1;" + System.lineSeparator());
                }

                target.commit();
                ValidationSummary validationSummary = validateCounts(source, target, tables.values());
                writeValidationReport(config.validationFile(), validationSummary);

                if (config.baselineFlyway()) {
                    baselineFlyway(config);
                }

                System.out.println("Migration completed successfully.");
                System.out.println("Backup SQL written to: " + config.outputFile().toAbsolutePath());
                System.out.println("Validation report written to: " + config.validationFile().toAbsolutePath());
            }
        }
    }

    private static void createTargetDatabaseIfMissing(Connection targetServer, String databaseName) throws SQLException {
        try (Statement statement = targetServer.createStatement()) {
            statement.execute("CREATE DATABASE IF NOT EXISTS " + quoteMysqlIdentifier(databaseName)
                + " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        }
    }

    private static void ensureSafeTargetState(Connection target, boolean allowTargetReset) throws SQLException {
        List<String> existingTables = new ArrayList<>();
        DatabaseMetaData metaData = target.getMetaData();
        try (ResultSet tables = metaData.getTables(target.getCatalog(), null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (tableName != null && !tableName.isBlank()) {
                    existingTables.add(tableName);
                }
            }
        }

        List<String> userTables = existingTables.stream()
            .filter(name -> !"flyway_schema_history".equalsIgnoreCase(name))
            .toList();

        if (userTables.isEmpty()) {
            return;
        }

        if (!allowTargetReset) {
            throw new IllegalStateException(
                "Target MySQL database already contains tables. Set ALLOW_TARGET_RESET=true to let the migration tool clear the target first."
            );
        }

        try (Statement statement = target.createStatement()) {
            statement.execute("SET FOREIGN_KEY_CHECKS = 0");
            for (String tableName : userTables) {
                statement.execute("DROP TABLE IF EXISTS " + quoteMysqlIdentifier(tableName));
            }
            statement.execute("SET FOREIGN_KEY_CHECKS = 1");
        }
        target.commit();
    }

    private static Map<String, TableInfo> loadTables(Connection source) throws SQLException {
        Map<String, TableInfo> tables = new LinkedHashMap<>();
        DatabaseMetaData metaData = source.getMetaData();
        String sourceSchema = Optional.ofNullable(source.getSchema()).orElse("PUBLIC");

        try (ResultSet tableResult = metaData.getTables(null, sourceSchema, "%", new String[]{"TABLE"})) {
            while (tableResult.next()) {
                String tableName = tableResult.getString("TABLE_NAME");
                String schemaName = tableResult.getString("TABLE_SCHEM");
                if (tableName == null || tableName.isBlank() || !isApplicationTable(schemaName, tableName)) {
                    continue;
                }

                List<ColumnInfo> columns = loadColumns(metaData, schemaName, tableName);
                List<String> primaryKeys = loadPrimaryKeys(metaData, schemaName, tableName);
                List<ForeignKeyInfo> foreignKeys = loadForeignKeys(metaData, schemaName, tableName);
                tables.put(tableName, new TableInfo(tableName, columns, primaryKeys, foreignKeys));
            }
        }

        return tables;
    }

    private static boolean isApplicationTable(String schemaName, String tableName) {
        if (tableName.startsWith("SYSTEM_")) {
            return false;
        }
        if (schemaName == null || schemaName.isBlank()) {
            return true;
        }
        String normalizedSchema = schemaName.toUpperCase(Locale.ROOT);
        return !"INFORMATION_SCHEMA".equals(normalizedSchema) && !"PG_CATALOG".equals(normalizedSchema);
    }

    private static List<ColumnInfo> loadColumns(DatabaseMetaData metaData, String schemaName, String tableName) throws SQLException {
        List<ColumnInfo> columns = new ArrayList<>();
        try (ResultSet columnResult = metaData.getColumns(null, schemaName, tableName, "%")) {
            while (columnResult.next()) {
                columns.add(new ColumnInfo(
                    columnResult.getString("COLUMN_NAME"),
                    columnResult.getInt("DATA_TYPE"),
                    columnResult.getString("TYPE_NAME"),
                    columnResult.getInt("COLUMN_SIZE"),
                    columnResult.getInt("DECIMAL_DIGITS"),
                    columnResult.getInt("NULLABLE") == DatabaseMetaData.columnNullable,
                    "YES".equalsIgnoreCase(columnResult.getString("IS_AUTOINCREMENT")),
                    normalizeDefaultValue(columnResult.getString("COLUMN_DEF"), columnResult.getInt("DATA_TYPE"))
                ));
            }
        }
        return columns;
    }

    private static List<String> loadPrimaryKeys(DatabaseMetaData metaData, String schemaName, String tableName) throws SQLException {
        List<PrimaryKeyColumn> keys = new ArrayList<>();
        try (ResultSet primaryKeyResult = metaData.getPrimaryKeys(null, schemaName, tableName)) {
            while (primaryKeyResult.next()) {
                keys.add(new PrimaryKeyColumn(
                    primaryKeyResult.getString("COLUMN_NAME"),
                    primaryKeyResult.getShort("KEY_SEQ")
                ));
            }
        }
        return keys.stream()
            .sorted(Comparator.comparingInt(PrimaryKeyColumn::position))
            .map(PrimaryKeyColumn::columnName)
            .toList();
    }

    private static List<ForeignKeyInfo> loadForeignKeys(DatabaseMetaData metaData, String schemaName, String tableName) throws SQLException {
        Map<String, List<ForeignKeyColumn>> grouped = new LinkedHashMap<>();
        try (ResultSet foreignKeyResult = metaData.getImportedKeys(null, schemaName, tableName)) {
            while (foreignKeyResult.next()) {
                String foreignKeyName = foreignKeyResult.getString("FK_NAME");
                if (foreignKeyName == null || foreignKeyName.isBlank()) {
                    foreignKeyName = "fk_" + tableName + "_" + foreignKeyResult.getString("FKCOLUMN_NAME");
                }
                grouped.computeIfAbsent(foreignKeyName, ignored -> new ArrayList<>()).add(new ForeignKeyColumn(
                    foreignKeyResult.getString("FKCOLUMN_NAME"),
                    foreignKeyResult.getString("PKTABLE_NAME"),
                    foreignKeyResult.getString("PKCOLUMN_NAME"),
                    foreignKeyResult.getShort("KEY_SEQ"),
                    foreignKeyResult.getShort("UPDATE_RULE"),
                    foreignKeyResult.getShort("DELETE_RULE")
                ));
            }
        }

        List<ForeignKeyInfo> foreignKeys = new ArrayList<>();
        for (Map.Entry<String, List<ForeignKeyColumn>> entry : grouped.entrySet()) {
            List<ForeignKeyColumn> columns = entry.getValue().stream()
                .sorted(Comparator.comparingInt(ForeignKeyColumn::position))
                .toList();
            ForeignKeyColumn firstColumn = columns.get(0);
            foreignKeys.add(new ForeignKeyInfo(
                entry.getKey(),
                columns.stream().map(ForeignKeyColumn::fkColumn).toList(),
                firstColumn.pkTable(),
                columns.stream().map(ForeignKeyColumn::pkColumn).toList(),
                toMysqlRule(firstColumn.updateRule()),
                toMysqlRule(firstColumn.deleteRule())
            ));
        }
        return foreignKeys;
    }

    private static String normalizeDefaultValue(String rawDefault, int jdbcType) {
        if (rawDefault == null || rawDefault.isBlank()) {
            return null;
        }

        String value = rawDefault.trim();
        if ("NULL".equalsIgnoreCase(value)) {
            return null;
        }
        if (jdbcType == Types.BOOLEAN || jdbcType == Types.BIT) {
            if ("TRUE".equalsIgnoreCase(value)) {
                return "1";
            }
            if ("FALSE".equalsIgnoreCase(value)) {
                return "0";
            }
        }
        if ("CURRENT_TIMESTAMP()".equalsIgnoreCase(value) || "CURRENT_TIMESTAMP".equalsIgnoreCase(value)) {
            return "CURRENT_TIMESTAMP";
        }
        return value;
    }

    private static String toMysqlRule(short rule) {
        return switch (rule) {
            case DatabaseMetaData.importedKeyCascade -> "CASCADE";
            case DatabaseMetaData.importedKeySetNull -> "SET NULL";
            case DatabaseMetaData.importedKeyRestrict -> "RESTRICT";
            case DatabaseMetaData.importedKeyNoAction -> "NO ACTION";
            default -> null;
        };
    }

    private static String buildCreateTableSql(TableInfo table) {
        List<String> definitions = new ArrayList<>();
        for (ColumnInfo column : table.columns()) {
            StringBuilder definition = new StringBuilder();
            definition.append(quoteMysqlIdentifier(column.name())).append(' ').append(toMysqlColumnType(column));
            if (!column.nullable()) {
                definition.append(" NOT NULL");
            }
            if (column.defaultValue() != null && !column.autoIncrement()) {
                definition.append(" DEFAULT ").append(formatDefaultValue(column.defaultValue(), column.jdbcType()));
            }
            if (column.autoIncrement()) {
                definition.append(" AUTO_INCREMENT");
            }
            definitions.add(definition.toString());
        }

        if (!table.primaryKeys().isEmpty()) {
            String primaryKeySql = table.primaryKeys().stream()
                .map(DatabaseMigrationTool::quoteMysqlIdentifier)
                .collect(Collectors.joining(", "));
            definitions.add("PRIMARY KEY (" + primaryKeySql + ")");
        }

        return "CREATE TABLE " + quoteMysqlIdentifier(table.name()) + " (\n  "
            + String.join(",\n  ", definitions)
            + "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
    }

    private static String toMysqlColumnType(ColumnInfo column) {
        return switch (column.jdbcType()) {
            case Types.BIGINT -> "BIGINT";
            case Types.INTEGER -> "INT";
            case Types.SMALLINT -> "SMALLINT";
            case Types.TINYINT -> "TINYINT";
            case Types.BOOLEAN, Types.BIT -> "TINYINT(1)";
            case Types.FLOAT -> "FLOAT";
            case Types.REAL -> "REAL";
            case Types.DOUBLE -> "DOUBLE";
            case Types.NUMERIC, Types.DECIMAL -> decimalType(column);
            case Types.CHAR -> "CHAR(" + Math.max(column.size(), 1) + ")";
            case Types.VARCHAR, Types.NVARCHAR, Types.LONGNVARCHAR -> varcharType(column.size());
            case Types.LONGVARCHAR, Types.CLOB, Types.NCLOB -> "LONGTEXT";
            case Types.DATE -> "DATE";
            case Types.TIME, Types.TIME_WITH_TIMEZONE -> "TIME";
            case Types.TIMESTAMP, Types.TIMESTAMP_WITH_TIMEZONE -> "DATETIME(6)";
            case Types.BINARY, Types.VARBINARY, Types.LONGVARBINARY, Types.BLOB -> "LONGBLOB";
            default -> fallbackType(column.typeName(), column.size(), column.scale());
        };
    }

    private static String decimalType(ColumnInfo column) {
        if (column.size() > 0 && column.scale() >= 0) {
            return "DECIMAL(" + column.size() + "," + column.scale() + ")";
        }
        return "DECIMAL(19,2)";
    }

    private static String varcharType(int size) {
        if (size <= 0) {
            return "VARCHAR(255)";
        }
        if (size > 65535) {
            return "LONGTEXT";
        }
        return "VARCHAR(" + size + ")";
    }

    private static String fallbackType(String typeName, int size, int scale) {
        if (typeName == null) {
            return "LONGTEXT";
        }

        String normalized = typeName.toUpperCase(Locale.ROOT);
        if (normalized.contains("BOOLEAN")) {
            return "TINYINT(1)";
        }
        if (normalized.contains("TEXT")) {
            return "LONGTEXT";
        }
        if (normalized.contains("BLOB") || normalized.contains("BINARY")) {
            return "LONGBLOB";
        }
        if (normalized.contains("TIMESTAMP")) {
            return "DATETIME(6)";
        }
        if (normalized.contains("DATE")) {
            return "DATE";
        }
        if (normalized.contains("TIME")) {
            return "TIME";
        }
        if (normalized.contains("DECIMAL") || normalized.contains("NUMERIC")) {
            return size > 0 ? "DECIMAL(" + size + "," + Math.max(scale, 0) + ")" : "DECIMAL(19,2)";
        }
        return "LONGTEXT";
    }

    private static String formatDefaultValue(String value, int jdbcType) {
        if ("CURRENT_TIMESTAMP".equalsIgnoreCase(value)) {
            return "CURRENT_TIMESTAMP";
        }
        if (jdbcType == Types.BOOLEAN || jdbcType == Types.BIT) {
            return ("1".equals(value) || "TRUE".equalsIgnoreCase(value)) ? "1" : "0";
        }
        if (isNumericType(jdbcType) && isPlainNumber(value)) {
            return value;
        }
        return "'" + escapeSql(value) + "'";
    }

    private static boolean isNumericType(int jdbcType) {
        return switch (jdbcType) {
            case Types.BIGINT, Types.INTEGER, Types.SMALLINT, Types.TINYINT, Types.FLOAT, Types.REAL, Types.DOUBLE, Types.NUMERIC, Types.DECIMAL -> true;
            default -> false;
        };
    }

    private static boolean isPlainNumber(String value) {
        try {
            new BigDecimal(value);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    private static void exportAndImportRows(Connection source, Connection target, TableInfo table, BufferedWriter writer)
        throws SQLException, IOException {
        try (
            Statement statement = source.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM " + quoteH2Identifier(table.name()))
        ) {
            int rowCount = 0;
            while (resultSet.next()) {
                String insertSql = buildInsertSql(table, resultSet);
                executeStatement(target, insertSql);
                writer.write(insertSql);
                writer.write(System.lineSeparator());
                rowCount++;
            }
            if (rowCount > 0) {
                writer.write(System.lineSeparator());
            }
        }
    }

    private static String buildInsertSql(TableInfo table, ResultSet resultSet) throws SQLException {
        List<String> values = new ArrayList<>();
        for (ColumnInfo column : table.columns()) {
            values.add(toSqlLiteral(resultSet.getObject(column.name()), column.jdbcType()));
        }

        String columnsSql = table.columns().stream()
            .map(ColumnInfo::name)
            .map(DatabaseMigrationTool::quoteMysqlIdentifier)
            .collect(Collectors.joining(", "));
        return "INSERT INTO " + quoteMysqlIdentifier(table.name()) + " (" + columnsSql + ") VALUES ("
            + String.join(", ", values) + ");";
    }

    private static String toSqlLiteral(Object value, int jdbcType) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Boolean boolValue) {
            return boolValue ? "1" : "0";
        }
        if (value instanceof Number numberValue && !(value instanceof BigDecimal)) {
            return numberValue.toString();
        }
        if (value instanceof BigDecimal decimalValue) {
            return decimalValue.toPlainString();
        }
        if (value instanceof Timestamp timestampValue) {
            return "'" + DATE_TIME_FORMATTER.format(timestampValue.toLocalDateTime()) + "'";
        }
        if (value instanceof Date dateValue) {
            return "'" + dateValue.toLocalDate() + "'";
        }
        if (value instanceof Time timeValue) {
            return "'" + TIME_FORMATTER.format(timeValue.toLocalTime()) + "'";
        }
        if (value instanceof byte[] bytes) {
            return "X'" + toHex(bytes) + "'";
        }
        if (jdbcType == Types.BOOLEAN || jdbcType == Types.BIT) {
            return "TRUE".equalsIgnoreCase(String.valueOf(value)) ? "1" : "0";
        }
        return "'" + escapeSql(String.valueOf(value)) + "'";
    }

    private static String buildForeignKeySql(String tableName, ForeignKeyInfo foreignKey) {
        String fkColumns = foreignKey.fkColumns().stream()
            .map(DatabaseMigrationTool::quoteMysqlIdentifier)
            .collect(Collectors.joining(", "));
        String pkColumns = foreignKey.pkColumns().stream()
            .map(DatabaseMigrationTool::quoteMysqlIdentifier)
            .collect(Collectors.joining(", "));

        StringBuilder sql = new StringBuilder()
            .append("ALTER TABLE ")
            .append(quoteMysqlIdentifier(tableName))
            .append(" ADD CONSTRAINT ")
            .append(quoteMysqlIdentifier(foreignKey.name()))
            .append(" FOREIGN KEY (")
            .append(fkColumns)
            .append(") REFERENCES ")
            .append(quoteMysqlIdentifier(foreignKey.pkTable()))
            .append(" (")
            .append(pkColumns)
            .append(')');

        if (foreignKey.updateRule() != null) {
            sql.append(" ON UPDATE ").append(foreignKey.updateRule());
        }
        if (foreignKey.deleteRule() != null) {
            sql.append(" ON DELETE ").append(foreignKey.deleteRule());
        }
        sql.append(';');
        return sql.toString();
    }

    private static ValidationSummary validateCounts(Connection source, Connection target, Collection<TableInfo> tables) throws SQLException {
        List<TableValidation> validations = new ArrayList<>();
        for (TableInfo table : tables) {
            long sourceCount = countRows(source, quoteH2Identifier(table.name()));
            long targetCount = countRows(target, quoteMysqlIdentifier(table.name()));
            validations.add(new TableValidation(table.name(), sourceCount, targetCount, sourceCount == targetCount));
        }
        boolean success = validations.stream().allMatch(TableValidation::match);
        if (!success) {
            throw new IllegalStateException("Row count validation failed. See validation report for details.");
        }
        return new ValidationSummary(validations, success);
    }

    private static long countRows(Connection connection, String quotedTableName) throws SQLException {
        try (
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) FROM " + quotedTableName)
        ) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private static void writeValidationReport(Path validationFile, ValidationSummary validationSummary) throws IOException {
        try (BufferedWriter writer = Files.newBufferedWriter(validationFile, StandardCharsets.UTF_8)) {
            writer.write("Validation generated at " + LocalDateTime.now());
            writer.write(System.lineSeparator());
            writer.write(System.lineSeparator());
            for (TableValidation validation : validationSummary.tables()) {
                writer.write(validation.tableName()
                    + " | source=" + validation.sourceRowCount()
                    + " | target=" + validation.targetRowCount()
                    + " | match=" + validation.match());
                writer.write(System.lineSeparator());
            }
            writer.write(System.lineSeparator());
            writer.write("overallSuccess=" + validationSummary.success());
            writer.write(System.lineSeparator());
        }
    }

    private static void baselineFlyway(MigrationConfig config) throws SQLException {
        String latestVersion = discoverLatestMigrationVersion();
        if (latestVersion == null) {
            return;
        }

        try (Connection connection = DriverManager.getConnection(config.targetUrl(), config.targetUsername(), config.targetPassword())) {
            if (hasFlywayHistory(connection)) {
                return;
            }
        }

        Flyway.configure()
            .dataSource(config.targetUrl(), config.targetUsername(), config.targetPassword())
            .baselineVersion(latestVersion)
            .baselineDescription("Imported from H2 local profile")
            .load()
            .baseline();
    }

    private static boolean hasFlywayHistory(Connection connection) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet tables = metaData.getTables(connection.getCatalog(), null, "flyway_schema_history", new String[]{"TABLE"})) {
            return tables.next();
        }
    }

    private static String discoverLatestMigrationVersion() {
        Path migrationDir = Paths.get("src", "main", "resources", "db", "migration");
        if (!Files.isDirectory(migrationDir)) {
            return null;
        }

        try (var stream = Files.list(migrationDir)) {
            return stream
                .map(path -> path.getFileName().toString())
                .map(MIGRATION_FILE_PATTERN::matcher)
                .filter(Matcher::matches)
                .map(matcher -> matcher.group("version"))
                .map(Integer::parseInt)
                .max(Integer::compareTo)
                .map(String::valueOf)
                .orElse(null);
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to inspect Flyway migrations.", ex);
        }
    }

    private static void executeStatement(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private static String quoteMysqlIdentifier(String identifier) {
        return "`" + identifier.replace("`", "``") + "`";
    }

    private static String quoteH2Identifier(String identifier) {
        return "\"" + identifier.replace("\"", "\"\"") + "\"";
    }

    private static String escapeSql(String value) {
        return value.replace("\\", "\\\\").replace("'", "''");
    }

    private static String toHex(byte[] bytes) {
        StringBuilder builder = new StringBuilder(bytes.length * 2);
        for (byte value : bytes) {
            builder.append(String.format("%02X", value));
        }
        return builder.toString();
    }

    private record MigrationConfig(
        String sourceUrl,
        String sourceUsername,
        String sourcePassword,
        String targetUrl,
        String targetServerUrl,
        String targetDatabase,
        String targetUsername,
        String targetPassword,
        boolean allowTargetReset,
        boolean baselineFlyway,
        Path outputFile,
        Path validationFile
    ) {
        private static MigrationConfig fromEnvironment() {
            String sourceUrl = requireEnv("SOURCE_DB_URL");
            String sourceUsername = envOrDefault("SOURCE_DB_USERNAME", "sa");
            String sourcePassword = envOrDefault("SOURCE_DB_PASSWORD", "");
            String targetUrl = requireEnv("DB_URL");
            String targetUsername = requireEnv("DB_USERNAME");
            String targetPassword = requireEnv("DB_PASSWORD");

            if (!targetUrl.toLowerCase(Locale.ROOT).startsWith("jdbc:mysql://")) {
                throw new IllegalStateException("DB_URL must point to a MySQL database for the migration target.");
            }

            MysqlTarget mysqlTarget = parseMysqlUrl(targetUrl);
            Path outputFile = resolvePath(envOrDefault("DB_MIGRATION_OUTPUT_FILE", Paths.get("..", "backups", "db-migration", "backup.sql").toString()));
            Path validationFile = resolvePath(envOrDefault("DB_MIGRATION_VALIDATION_FILE", Paths.get("..", "backups", "db-migration", "validation-report.txt").toString()));

            return new MigrationConfig(
                sourceUrl,
                sourceUsername,
                sourcePassword,
                targetUrl,
                mysqlTarget.serverUrl(),
                mysqlTarget.databaseName(),
                targetUsername,
                targetPassword,
                Boolean.parseBoolean(envOrDefault("ALLOW_TARGET_RESET", "false")),
                !"false".equalsIgnoreCase(envOrDefault("BASELINE_FLYWAY_AFTER_IMPORT", "true")),
                outputFile,
                validationFile
            );
        }

        private static MysqlTarget parseMysqlUrl(String url) {
            Matcher matcher = MYSQL_URL_PATTERN.matcher(url);
            if (!matcher.matches()) {
                throw new IllegalStateException("DB_URL must follow jdbc:mysql://host:port/database format.");
            }

            String hostPort = matcher.group("hostport");
            String databaseName = matcher.group("db");
            String query = matcher.group("query");
            String serverUrl = "jdbc:mysql://" + hostPort + "/" + (query == null ? "" : query);
            return new MysqlTarget(serverUrl, databaseName);
        }

        private static Path resolvePath(String pathValue) {
            return Paths.get(pathValue).normalize().toAbsolutePath();
        }
    }

    private record MysqlTarget(String serverUrl, String databaseName) {
    }

    private record TableInfo(String name, List<ColumnInfo> columns, List<String> primaryKeys, List<ForeignKeyInfo> foreignKeys) {
    }

    private record ColumnInfo(
        String name,
        int jdbcType,
        String typeName,
        int size,
        int scale,
        boolean nullable,
        boolean autoIncrement,
        String defaultValue
    ) {
    }

    private record ForeignKeyInfo(
        String name,
        List<String> fkColumns,
        String pkTable,
        List<String> pkColumns,
        String updateRule,
        String deleteRule
    ) {
    }

    private record ForeignKeyColumn(
        String fkColumn,
        String pkTable,
        String pkColumn,
        int position,
        short updateRule,
        short deleteRule
    ) {
    }

    private record PrimaryKeyColumn(String columnName, int position) {
    }

    private record TableValidation(String tableName, long sourceRowCount, long targetRowCount, boolean match) {
    }

    private record ValidationSummary(List<TableValidation> tables, boolean success) {
    }

    private static String requireEnv(String name) {
        String value = System.getenv(name);
        if (value == null || value.isBlank()) {
            throw new IllegalStateException(name + " is required.");
        }
        return value.trim();
    }

    private static String envOrDefault(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
